<!-- Winscreen.web.id -->

                          //<![CDATA[
                          $(document).ready(function(){
                            $('.comments .comments-content .avatar-image-container img').each(function(){
                              this.src = this.src.replace('/s35-c/', '/s80-c/');
                            });
                            $('.comments .comments-content .avatar-image-container img').each(function(){
                              this.src = this.src.replace('/s35/', '/s80-c/');
                            });
                          });
